/* AI provider config (optional). Generated by tools-v8/build.mjs: when OPENROUTER_KEY is set at build time this
 * file carries an obfuscated key, otherwise null. Obfuscation is NOT protection: anyone can extract the key. */
window.HT_AI_CFG = null;
